### ISSUE TITLE
Column collation needs to be explicit set

### ISSUE THREAD

**Issue by thx123** [tom--/Collation-to-Charset-Table#1]
Hi Tom,

Thanks for your great tool. I've used it to generate charset_tables successfully for collations other than 'utf8_general_ci', but I have had to make a minor change to your code, by explicitly setting the 'mychar' column's collation to $collation as well; otherwise mysql would defaults it to 'utf8_general_ci', instead of inheriting it from the database or table collation.

I don't have read-write access to your project so committed the change to my fork, not sure if that's the right way to do it as this is my first git commit:

https://github.com/thx123/Collation-to-Charset-Table.git

Again, thanks a lot for your nice work.

**Comment by thx123** [comment]
```
mysql> show create table my_table;
+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table    | Create Table                                                                                                                                                                                                     |
+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| my_table | CREATE TABLE `my_table` (
  `dec` int(11) NOT NULL,
  `mychar` char(1) CHARACTER SET utf8 COLLATE utf8_swedish_ci NOT NULL,
  `hex` char(4) NOT NULL,
  PRIMARY KEY (`dec`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 |
+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show full columns from my_table;
+--------+---------+-----------------+------+-----+---------+-------+---------------------------------+---------+
| Field  | Type    | Collation       | Null | Key | Default | Extra | Privileges                      | Comment |
+--------+---------+-----------------+------+-----+---------+-------+---------------------------------+---------+
| dec    | int(11) | NULL            | NO   | PRI | NULL    |       | select,insert,update,references |         |
| mychar | char(1) | utf8_swedish_ci | NO   |     | NULL    |       | select,insert,update,references |         |
| hex    | char(4) | utf8_general_ci | NO   |     | NULL    |       | select,insert,update,references |         |
+--------+---------+-----------------+------+-----+---------+-------+---------------------------------+---------+
3 rows in set (0.00 sec)
```

Note that the other char column hex, which is not explicitly set to use 'utf8_swedish_ci' collation, is set to use the default 'utf8_general_ci' collation by mysql implicitly. Without this fix, the PHP scripts would generate the same outputs for all other collations as the one for the 'utf8_swedish_ci' collation.

**Comment by tom--** [comment]
@thx123 I'm sorry to have neglected your input for so long.

You can get your changes into this repo by sending a Pull Request. Github docs explain.

**Comment by tom--** [comment]
I incorporated your change in this, the Late 2015 rewrite.

**Comment by thx123** [comment]
Hi Tom,

Sorry I didn't get a chance to get back to you and push the change myself. Thanks for taking care of it!
