### ISSUE TITLE
Don't drop the schema

### ISSUE THREAD

**Issue by tom--** [tom--/Collation-to-Charset-Table#3]
https://github.com/tom--/Collation-to-Charset-Table/pull/2#issue-214218864

**Comment by barryhunter** [comment]
Thanks, yes. Dont think it should be deleting the schema/database itself. Seems OTT. It could just do DROP TABLE IF EXISTS {mytable}; so its free to create the table as needed.

**Comment by tom--** [comment]
Fixed in today's rewrites
